### ISSUE TITLE
Installation of elasticsearch fails when running offline

### ISSUE THREAD

**Issue by knrc** [openshift-istio/openshift-ansible#12]
The error message is

create Pod elasticsearch-0 in StatefulSet elasticsearch failed error: Pod "elasticsearch-0" is invalid: spec.containers[0].image: Invalid value: " ": must not have leading or trailing whitespace

This is related to the way in which the elasticsearch installation uses triggers to populate the image information from the imagestreams.

**Comment by geoand** [comment]
I just saw this issue as well. 
Unfortunately I can't seem to reproduce it consistently

**Comment by knrc** [comment]
@geoand I was able to reproduce this reasonably frequently while travelling, I'll take a look at it today since it's now also impacting you.

**Comment by geoand** [comment]
@knrc Thanks! 

It's obviously not a big problem at the moment since I can get around the issue by manually setting the image

**Comment by knrc** [comment]
@geoand Give this version a try, if the ES image is available offline then it should now deploy cleanly

**Comment by geoand** [comment]
@knrc Worked like a charm!
