### ISSUE TITLE
Kiali pod is always installed, it should only be done when username/password are provided

### ISSUE THREAD

**Issue by knrc** [openshift-istio/openshift-ansible#14]

**Comment by gbaufake** [comment]
@knrc 
I think it may be a existing problem 

oc process -f https://raw.githubusercontent.com/openshift-istio/openshift-ansible/istio-3.10-0.8.0/istio/istio_installer_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=https://url:8443 -p=OPENSHIFT_ISTIO_INSTALL_AUTH=false | oc create -f -

logs attached 

[openshift-ansible-istio-installer-job-d6hxd.log](https://github.com/openshift-istio/openshift-ansible/files/2164233/openshift-ansible-istio-installer-job-d6hxd.log)

**Comment by knrc** [comment]
@gbaufake This log file is from an old installer, can you update to the latest and try again?

**Comment by gbaufake** [comment]
that is odd I tried this some hours ago.

**Comment by knrc** [comment]
@gbaufake Try changing the imagePullPolicy in the template to Always in that case, this will force OpenShift to download a new version rather than using any local copies.
