### ISSUE TITLE
openshift-ansible-istio-installer complete, but no pods started

### ISSUE THREAD

**Issue by mattmahoneyrh** [openshift-istio/openshift-ansible#15]
#### Description

When attempting to install 0.7.1 (could also be an issue with .0.8.0) openshift-ansible-istio-installer exists but NO pods are started. This happens intermittently when installing into Openshift v3.9.14.

Jenkins job output example below. 

##### Version

Please put the following version information in the code block
indicated below.

```
VERSION INFORMATION HERE PLEASE
```

##### Expected Results
Expected all istio pods to start successfully.

```
Example Jenkins pipeline output, which contains

[Istio-Downstream] Running shell script
+ oc get namespace bookinfo
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Create Pod to Install Istio Downstream)
[Pipeline] dir
Running in /home/jenkins/workspace/Istio-Downstream/openshift-ansible/istio
[Pipeline] {
[Pipeline] sh
[istio] Running shell script
+ oc new-project istio-system
Now using project "istio-system" on server "<hostname>".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.
[Pipeline] sh
[istio] Running shell script
+ oc create sa openshift-ansible
serviceaccount "openshift-ansible" created
[Pipeline] sh
[istio] Running shell script
+ oc adm policy add-scc-to-user privileged -z openshift-ansible
scc "privileged" added to: ["system:serviceaccount:istio-system:openshift-ansible"]
[Pipeline] sh
[istio] Running shell script
+ oc adm policy add-cluster-role-to-user cluster-admin -z openshift-ansible
cluster role "cluster-admin" added: "openshift-ansible"
[Pipeline] sh
[istio] Running shell script
+ oc process -f https://raw.githubusercontent.com/openshift-istio/openshift-ansible/istio-3.9-0.7.1/istio/istio_installer_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=<hostname>
+ oc create -f -
configmap "install.istio.inventory" created
job "openshift-ansible-istio-installer-job" created
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

**Comment by tvieira** [comment]
Actually, the job does not complete. The event describes:

`Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: service "istio-sidecar-injector" not found`

**Comment by knrc** [comment]
Can you please explain what you mean by complete?  The installer job starts other deployments however it will finish before those are deployed, especially if any images need to be downloaded.

**Comment by mattmahoneyrh** [comment]
@knrc, all that is meant by 'complete' is that the installer runs and then after some minutes is no longer present (i.e. the installer pod is in Running state for some time, and then no longer exists). 

Example of the symptom:
$ oc project
Using project "istio-system" on server "<hostname>:8443".
$ oc get jobs
NAME                                    DESIRED   SUCCESSFUL   AGE
openshift-ansible-istio-installer-job   1         0            47m
$ oc get pods
No resources found.

**Comment by knrc** [comment]
@mattmahoneyrh What state were the other deployments in?  These would finish after the job since they are async.

**Comment by knrc** [comment]
I've updated the installer so the webhook is not called for pods in the istio-system namespace, this removes the confusion with @tvieira's comment referencing the webhook from a previous installation and should allow you to see the other pods while they are pulling their images.
