### ISSUE TITLE
Kiali Route is not being exposed

### ISSUE THREAD

**Issue by gbaufake** [openshift-istio/openshift-ansible#16]
#### Description

When you install Kiali via openshift-ansible without kiali parameters: 

`oc process -f https://raw.githubusercontent.com/openshift-istio/openshift-ansible/istio-3.10-0.8.0/istio/istio_installer_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=openshift-url:8443` 

kiali is being installed without route exposed. (maybe kiali shouldn't be installed on this case, but if so, kiali route should be exposed as well)

When you install Kiali via openshift-ansible with kiali parameters:

`oc process -f https://raw.githubusercontent.com/openshift-istio/openshift-ansible/istio-3.10-0.8.0/istio/istio_installer_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=openshift_url:8443 -p=OPENSHIFT_ISTIO_KIALI_USERNAME=admin -p=OPENSHIFT_ISTIO_KIALI_PASSWORD=admin
+ oc create -f `

kiali is being installed (as expected) but the route is not being exposed.

![image](https://user-images.githubusercontent.com/2313749/41435690-0e423886-6ff6-11e8-95c7-e3eae56d5281.png)

##### Version
 `ansible --version`
> ansible 2.5.2
  config file = /home/gbaufake/Redhat/istio/install/ansible/ansible.cfg
  configured module search path = [u'/home/gbaufake/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

**Comment by gbaufake** [comment]
cc @tvieira @knrc

**Comment by knrc** [comment]
@gbaufake I've just tried installing using the latest installer and I cannot get kiali to install if the username/password is not provided, can you please try with the latest version and see whether this is still an issue?  There was a recent issue which may be related (#14)

**Comment by gbaufake** [comment]
@knrc 
Tried again.
it didn't install kiali (like you said it would)


but when I tried `oc process -f https://raw.githubusercontent.com/openshift-istio/openshift-ansible/istio-3.10-0.8.0/istio/istio_installer_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=https://openshift_url:8443 -p=OPENSHIFT_ISTIO_KIALI_USERNAME=admin -p=OPENSHIFT_ISTIO_KIALI_PASSWORD=admin`


but I didn't get kiali installed
![image](https://user-images.githubusercontent.com/2313749/41553557-79cfffba-7308-11e8-951a-fba53634d18b.png)

**Comment by knrc** [comment]
@gbaufake Can you send me the log from the installation job?  I've just tried this locally and see kiali being installed but there may be something in the log which shows an error.

**Comment by gbaufake** [comment]
Logs Attached
command used: 
`oc process -f https://raw.githubusercontent.com/openshift-istio/openshift-ansible/istio-3.10-0.8.0/istio/istio_installer_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=openshift_url:8443 -p=OPENSHIFT_ISTIO_KIALI_USERNAME=admin -p=OPENSHIFT_ISTIO_KIALI_PASSWORD=admin oc create -f -`

[openshift-ansible-istio-installer-job-tsdrw.log](https://github.com/openshift-istio/openshift-ansible/files/2113197/openshift-ansible-istio-installer-job-tsdrw.log)

**Comment by knrc** [comment]
Very strange, according to that log kiali was deployed

> deployment "kiali" created

Can you run

> oc describe deployment kiali

and see what it says?

**Comment by gbaufake** [comment]
Outdated issue. Closing this one
