### ISSUE TITLE
openshift-ansible-istio-installer-job isn't working when sidecar-injector.istio.io is activated

### ISSUE THREAD

**Issue by gbaufake** [openshift-istio/openshift-ansible#18]
#### Description
The openshift-ansible-installer-job is being prevented to be installed when sidecar-injector is enabled according to https://github.com/openshift-istio/openshift-ansible/blob/istio-3.10-0.8.0/istio/Installation.md#updating-the-master

![image](https://user-images.githubusercontent.com/2313749/41618359-564deeae-73d9-11e8-822c-671aa1cb4906.png)

**Comment by gbaufake** [comment]
I tested with 0.7.1 and 0.8.0 and the result is the same

**Comment by knrc** [comment]
The issue is likely an old installation not being cleaned up correctly, the latest installer now forcibly removes known artifacts before installation however you will need to remove the older mutatingwebhookconfiguration using the following before the new installer can be used.

> oc delete mutatingwebhookconfiguration istio-sidecar-injector

**Comment by gbaufake** [comment]
@knrc 
I tried with 0.8.0 and it seems there is no problem.
Since we are moving to istio 0.8.0, i'm closing this issue

**Comment by knrc** [comment]
@gbaufake Thanks for closing.  The only reason for the job not running would be an older webhook hanging around, we had previously applied this to every namespaces but now it's all except istio-system.  You should never see this using the current installer/webhook.
