### ISSUE TITLE
Updating Istio Namespace generates a problem on Installer

### ISSUE THREAD

**Issue by gbaufake** [openshift-istio/openshift-ansible#22]
#### Description
- Adding ` openshift.io/node-selector: region=infra` via `oc edit namespace istio-system`  to Istio System before installing leads to a problem on Installer.

Installer Logs attached
[openshift-ansible-istio-installer-job-8tfdt.log](https://github.com/openshift-istio/openshift-ansible/files/2151247/openshift-ansible-istio-installer-job-8tfdt.log)

**Comment by knrc** [comment]
I've just been working through this issue with Hayk, it should be fixed under issue #23
