### ISSUE TITLE
Istio removal template should be more forgiving

### ISSUE THREAD

**Issue by siamaksade** [openshift-istio/openshift-ansible#26]
The `istio_removal_template.yaml` template is very strict on the objects that should exist for removal. If an object is missing, it mostly fails instead of considering that object removed and move on to the next object.

This can possibly be achieved by setting most of enquiry tasks in the removal playbook  `ignore_errors: true` and make the following delete tasks conditional on if the object exists

**Comment by knrc** [comment]
@siamaksade The removal process is also invoked during installation so runs on a clean system without failure, could you send me a log of this failure?

**Comment by knrc** [comment]
Closing this as stale since the removal process has worked this way for a long time.
