### ISSUE TITLE
Elasticsearch is falling with limit of 512Mi

### ISSUE THREAD

**Issue by gbaufake** [openshift-istio/openshift-ansible#27]
#### Description

Deploying Istio 0.8 with 
`oc process -f https://raw.githubusercontent.com/openshift-istio/openshift-ansible/istio-3.10-0.8.0/istio/istio_installer_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=https://MASTER_URL:8443 -p=OPENSHIFT_ISTIO_INSTALL_AUTH=true`

causes a problem on elasticsearch due to a limit on the pod https://github.com/openshift-istio/openshift-ansible/blob/2b5d08650ec3156d174239e549e7dc795eee613d/roles/openshift_istio/files/elasticsearch.yml#L44-L47

`oc describe pod elasticsearch-0`                         
> Name:           elasticsearch-0
Namespace:      istio-system
Start Time:     Mon, 16 Jul 2018 10:27:00 -0300
Labels:         app=elasticsearch
                controller-revision-hash=elasticsearch-5c8fbb565f
                statefulset.kubernetes.io/pod-name=elasticsearch-0
Annotations:    openshift.io/scc=restricted
Status:         Running
IP:             10.130.1.62
Controlled By:  StatefulSet/elasticsearch
Containers:
  elasticsearch:
    Container ID:   docker://cdba7d930d1ded1b24fb5ca599d333247a22edde38d54526593751972fc82f77
    Image:          registry.centos.org/rhsyseng/elasticsearch@sha256:bca624bae5ec63d38896e4a02f652d245c69c98f0b7fae999ebc0dc6f5bc2eb2
    Image ID:       docker-pullable://registry.centos.org/rhsyseng/elasticsearch@sha256:bca624bae5ec63d38896e4a02f652d245c69c98f0b7fae999ebc0dc6f5bc2eb2
    Ports:          9200/TCP, 9300/TCP
    State:          Waiting
      **Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137**
      Started:      Mon, 16 Jul 2018 10:43:16 -0300
      Finished:     Mon, 16 Jul 2018 10:45:23 -0300
    Ready:          False
    Restart Count:  6

Can we add a way to increase this limit?

Best Regards,
Guilherme Baufaker Rêgo

**Comment by knrc** [comment]
@gbaufake  I have a local modification which can support the following option

>       --istio-elasticsearch-memory='': Specify the amount of memory to require for the elasticsearch deployments (experimental)

Before I commit and push this change to the istiooc command and the installer can I ask if there is anything else you need?  Should we be changing the default 512Mi to a more appropriate value?  Are there other elasticsearch configuration options you can envisage?

**Comment by gbaufake** [comment]
@pavolloffay  do you have any thought on what is the most appropriate value for default?

**Comment by pavolloffay** [comment]
This can go quite complex. The configuration should allow setting resources (mem, cpu), storage types and elasticsearch settings like shards and replicas. I am not sure if exposing all via flags is the way to go. But that is @knrc decision.

This jira summarizes what is important for ES configuration https://issues.jboss.org/browse/TRACING-61 It also contains default values used in ECL ES installer.

>  Should we be changing the default 512Mi to a more appropriate value? 

If the installer is aimed for production I would say yes. eg. ECL ES is using 8gb by default. https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html mentions that by default ES uses 1gb which should be adjusted before going to production.

**Comment by pavolloffay** [comment]
@knrc can be `istiooc` used to deploy istio (with jaeger) to production OC cluster? Or is it only for a local development which starts OC as local docker containers? 

Can be the installer playbook run without `istiooc`?

**Comment by knrc** [comment]
@pavolloffay istiooc is only for local development, however the installer job can be used to install into a cluster.  Neither are for production use.

The current elasticsearch yaml does not include options for configuring the cpu but we can add this if it would be useful for tech preview

https://github.com/openshift-istio/openshift-ansible/blob/istio-3.10-1.0.0-snapshot.0/roles/openshift_istio/files/elasticsearch.yml#L43-L47

I would want to defer more complex aspects until we get the operator functional, at this point we will be able to provide more flexibility in configuration.

I can add the cpu option and increase the default memory to 1G if you think this is worth doing.

**Comment by pavolloffay** [comment]
> @pavolloffay istiooc is only for local development, however the installer job can be used to install into a cluster. Neither are for production use.

What is for the production use then? 

> I can add the cpu option and increase the default memory to 1G if you think this is worth doing.

Nobody asked for CPU. I would let it as it is at the moment. The memory would be good to increase.

**Comment by knrc** [comment]
> What is for the production use then?

Nothing yet, we are only approaching TP release.

> Nobody asked for CPU. I would let it as it is at the moment. The memory would be good to increase.

Okay, I'll default the memory to 1G and push just this change.

**Comment by knrc** [comment]
There's a new istiooc binary released to support this option, https://github.com/openshift-istio/origin/releases/tag/istio-3.9-1.0.0-alpha2
