### ISSUE TITLE
Elasticsearch image 6.2.2 does not exist

### ISSUE THREAD

**Issue by siamaksade** [openshift-istio/openshift-ansible#3]
Even though the installer job for 0.7.1 uses `rhsyseng/elasticsearch:5.5.2`, it does create an imagestream for elasticsearch which references the non-existing `6.2.2` upstream tag which prevents the elasticsearch from being deployed:
https://registry.centos.org/rhsyseng/elasticsearch

registry.centos.org/rhsyseng/elasticsearch

**Comment by siamaksade** [comment]
@knrc

**Comment by knrc** [comment]
The template we were given does indeed define an imagestream for 6.2.2 as well as other versions however this does not prevent elasticsearch from deploying.

Can you provide more information on this?

In my local install I can see the imagestream information populated for 5.5.2, 6.1.2 and latest but not for 6.2.2 which is null.

**Comment by siamaksade** [comment]
I tried it again now but couldn't reproduce the elasticsearch statefulset failure. Possibly was due to other issues then
