### ISSUE TITLE
Istio installer job should be pinned to the master node

### ISSUE THREAD

**Issue by siamaksade** [openshift-istio/openshift-ansible#4]
Istio installer ansible playbooks assume running on the master node and fails if it runs on an app node. There should be a nodeselector in the job yaml to pin the job to the master node:

**Comment by siamaksade** [comment]
I managed to deploy it by adding the following nodeselector to the job:
```
        nodeSelector:
          node-role.kubernetes.io/master: "true"
```

I had to label the master node with `node-role.kubernetes.io/compute: "true"`. It's needed because In OCP 3.9 by default all pods have this nodeselector which results in a invalid combination on the job unless master is also labeled so:
```
        nodeSelector:
          node-role.kubernetes.io/master: "true"
          node-role.kubernetes.io/compute: "true"
```

**Comment by knrc** [comment]
This should now be fixed in the latest instructions, please give them a try and open a new issue if you still have problems.
