### ISSUE TITLE
Istio template fails to install - No such file or directory: '/etc/origin/master/admin.kubeconfig'

### ISSUE THREAD

**Issue by mocenas** [openshift-istio/openshift-ansible#6]
#### Description

Following installation manual at:
https://github.com/openshift-istio/openshift-ansible/blob/istio-3.9-0.7.1/istio/Installation.md
The openshift-ansible-istio-job pod ends with error.

Full error trace in attachment.
[istio_trace.txt](https://github.com/openshift-istio/openshift-ansible/files/2048742/istio_trace.txt)

**Comment by gbaufake** [comment]
I had the same situation

Logs attached
[openshift-ansible-istio-job-pc7dq.log](https://github.com/openshift-istio/openshift-ansible/files/2063164/openshift-ansible-istio-job-pc7dq.log)
[openshift-ansible-istio-job-gk59n.log](https://github.com/openshift-istio/openshift-ansible/files/2063165/openshift-ansible-istio-job-gk59n.log)

**Comment by knrc** [comment]
This should now be fixed by the latest instructions, please give them a try and open a new issue if you still have problems.
