### ISSUE TITLE
Include 'tracing' service for Jaeger

### ISSUE THREAD

**Issue by objectiser** [openshift-istio/openshift-ansible#7]
#### Description
Istio 0.8.0 introduces a `tracing` sub-chart that deploys the Jaeger backend - but in a limited form. It exposes `zipkin` and `tracing` services, `zipkin` as a collector for the zipkin formatted tracing data, and `tracing` to access a UI.

If users want the full Jaeger backend they currently need to set `tracing.jaeger.enabled=true` when installing with the helm chart.

I think it would be a good idea for the product to expose the same service `tracing`, to remain consistent with the community install.

##### Version
n/a

##### Expected Results
UI exposed via the `tracing` service, as well as `jaeger-query`.

**Comment by knrc** [comment]
I've added a service and route for tracing, it should now be possible to access it via an endpoint such as

https://tracing-istio-system.127.0.0.1.nip.io

The commit was https://github.com/openshift-istio/openshift-ansible/commit/00fec9b0759566d00c30a67b574544c0ffdf51f5
