### ISSUE TITLE
Istio template fails to install - certificate already exists

### ISSUE THREAD

**Issue by mocenas** [openshift-istio/openshift-ansible#8]
Execuing a command
``
oc new-app istio_installer_template.yaml --param=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=master.server
``
Causes the openshift-ansible-istio-job to fail, due to error:
 "Error from server (AlreadyExists): error when creating \"roles/openshift_istio/files/csr.yaml\": certificatesigningrequests.certificates.k8s.io \"istio-sidecar-injector.istio-system\" already exists"

attaching full log
[openshift-ansible-istio-job-khwjd.log](https://github.com/openshift-istio/openshift-ansible/files/2083606/openshift-ansible-istio-job-khwjd.log)

**Comment by knrc** [comment]
It looks as if this was not installed on a clean system, there must have been a CRD from a previous installation present.  Note that the installer can clean up an installation if openshift_istio_install is set to false in the inventory although I have not tested this on a partial installation.

I'll update the installers (0.7.1 and 0.8.0) to force a clean every time however note that for 0.8.0 the CSR is no longer required.

In the meantime run the following to clean up the previous installation
> oc delete csr istio-sidecar-injector.istio-system

**Comment by mocenas** [comment]
Thanks for help. What I write here is maybe different issue.

After using this command and installing istio on (probably) clear system. The istio-mixer-validator pod ends in crash-loop and reports some error with certificates.
Also openshift-ansible-istio pod reports some error.
Attaching logs from both pods.

[istio-mixer-validator-56488d76d7-f7dnt.log](https://github.com/openshift-istio/openshift-ansible/files/2093511/istio-mixer-validator-56488d76d7-f7dnt.log)
[openshift-ansible-istio-job-tklbx.log](https://github.com/openshift-istio/openshift-ansible/files/2093512/openshift-ansible-istio-job-tklbx.log)

**Comment by knrc** [comment]
It looks as if the job logs are showing a number of pre-existing artifacts (CRDs etc.) which are likely from a previous installation, it would be worth double checking this once I have the removal sorted out.

I'm not sure about the validator, I can double check this.  I assume this is 0.7.1 since validator is not included in the 0.8.0 installer.

**Comment by mocenas** [comment]
Sorry I forgot to specify version, yes it is a 0.7.1

**Comment by knrc** [comment]
Reopening to also address for 0.7.1

**Comment by knrc** [comment]
This has now been pushed for 0.7.1
